###########################################################
# Makefile generated by xIDE                               
#                                                          
# Project: spp_dev_b
# Configuration: Release
# Generated: ÐÇÆÚËÄ ¾ÅÔÂ 27 17:55:14 2012
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

OUTPUT=spp_dev_b
OUTDIR=E:/BlueCoreMaterial/ActnovaBTProject/sourcecode/spp_rfidreaderSep272012
HARDWARE_INDEX=1
DEFS=-DDEV_CASIRA -DNO_DEBUG 

DEBUGTRANSPORT=SPITRANS=USB SPIPORT=0
EXECUTION_MODE=native
STACKSIZE=512
TRANSPORT=raw
FIRMWARE=unified
PANIC_ON_PANIC=1
FIRMWAREIMAGE=
LIBRARY_VERSION=

LIBS=-lconnection -lspp -lregion -lservice -lbdaddr -lsdp_parse 
INPUTS=\
      spp_dev_b_leds.led\
      spp_dev_b_buttons.button\
      README.html\
      spp_dev_b.psr\
      led_timing.def\
      main.c\
      spp_dev_auth.c\
      spp_dev_b_leds.c\
      spp_dev_b_buttons.c\
      hal.c\
      errman.c\
      sppb.c\
      spp_dev_private.h\
      spp_dev_auth.h\
      spp_dev_b_leds.h\
      spp_dev_b_buttons.h\
      hal.h\
      hal_config.h\
      messagebase.h\
      errman.h\
      hal_private.h\
      sppb.h\
      bitmacro.h\
      debug.h\
      app_state.h\
      command_return_code.h\
      buzzer.h
# Project-specific options
characters=1
faultalerts=0
messages=1
pcvalue=0
primitives=0
timestamps=0

-include spp_dev_b.mak
include $(BLUELAB)/Makefile.vm
